import type { UserProfile } from './schema';

export const currentUser: Omit<UserProfile, 'id' | 'name' | 'bio' | 'image'> = {
  travelStyle: 'Adventure',
  dreamDestinations: ['Japan', 'New Zealand', 'Patagonia'],
  languagesSpoken: ['English', 'Spanish'],
  travelIntention: '50/50',
  interests: ['Hiking', 'Photography', 'Street Food'],
  age: 28,
  gender: 'Homme',
  verified: true,
};

export const possibleMatches: UserProfile[] = [
  {
    id: 'user1',
    name: 'Sophia',
    age: 26,
    gender: 'Femme',
    bio: 'Travel enthusiast looking for a partner to explore ancient ruins and enjoy beautiful beaches. Let\'s make some memories!',
    travelStyle: 'Cultural',
    dreamDestinations: ['Greece', 'Egypt', 'Peru'],
    languagesSpoken: ['English', 'French', 'Greek'],
    travelIntention: '50/50',
    interests: ['History', 'Scuba Diving', 'Wine Tasting'],
    verified: true,
    image: 'https://picsum.photos/800/1200',
  },
  {
    id: 'user2',
    name: 'James',
    age: 35,
    gender: 'Homme',
    bio: 'Entrepreneur who loves luxury travel. Looking to sponsor a trip for someone with a great sense of humor and a love for fine dining.',
    travelStyle: 'Luxe',
    dreamDestinations: ['Dubai', 'Monaco', 'Maldives'],
    languagesSpoken: ['English'],
    travelIntention: 'Sponsor',
    interests: ['Fine Dining', 'Yachting', 'Art Galleries'],
    verified: true,
    image: 'https://picsum.photos/800/1201',
  },
  {
    id: 'user3',
    name: 'Isabella',
    age: 22,
    gender: 'Femme',
    bio: 'Student and aspiring artist seeking a generous sponsor for an inspiring trip through Europe. I want to see the world!',
    travelStyle: 'Cultural',
    dreamDestinations: ['Italy', 'France', 'Spain'],
    languagesSpoken: ['English', 'Italian'],
    travelIntention: 'Sponsorisé',
    interests: ['Art', 'Museums', 'Cuisine'],
    verified: false,
    image: 'https://picsum.photos/800/1202',
  },
  {
    id: 'user4',
    name: 'Liam',
    age: 29,
    gender: 'Homme',
    bio: 'Digital nomad and avid hiker. I love being off the grid. Looking for a travel buddy for a backpacking trip in South America.',
    travelStyle: 'Adventure',
    dreamDestinations: ['Patagonia', 'Colombia', 'Ecuador'],
    languagesSpoken: ['English', 'Spanish'],
    travelIntention: '50/50',
    interests: ['Hiking', 'Mountaineering', 'Nature'],
    verified: true,
    image: 'https://picsum.photos/800/1203',
  },
  {
    id: 'user5',
    name: 'Chloe',
    age: 31,
    gender: 'Femme',
    bio: 'Organizing a group trip to a music festival in Belgium. Looking for fun-loving people to join our crew!',
    travelStyle: 'Relaxation',
    dreamDestinations: ['Belgium', 'Netherlands'],
    languagesSpoken: ['English', 'Dutch'],
    travelIntention: 'Groupe',
    interests: ['Music Festivals', 'Concerts', 'Socializing'],
    verified: true,
    image: 'https://picsum.photos/800/1204',
  },
   {
    id: 'user6',
    name: 'David',
    age: 42,
    gender: 'Homme',
    bio: 'Busy professional wanting to unwind. I prefer 5-star hotels and relaxing on the beach. Seeking a companion for a stress-free getaway.',
    travelStyle: 'Luxe',
    dreamDestinations: ['Thailand', 'Bali', 'Fiji'],
    languagesSpoken: ['English'],
    travelIntention: 'Sponsor',
    interests: ['Spas', 'Beaches', 'Cocktails'],
    verified: true,
    image: 'https://picsum.photos/800/1205',
  },
];
